version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: container-pgadmin-2
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    env_file:
      - ./.env
    restart: unless-stopped  

volumes:
  postgres_data: