name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'client/**'

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'server/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy Server to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PR_KEY }}
          script: |
            cd wordrix/server/
            git pull origin main
            docker-compose down
            docker-compose up -d --build

  deploy_client:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'client/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy Client to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PR_KEY }}
          script: |
            cd wordrix/client/
            git pull origin main
            docker-compose down
            docker-compose up -d --build
