name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  
  jobs:
  deploy_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy Client to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PR_KEY }}
          script: |
            cd wordrix/client/
            git pull origin main
            docker-compose down
            docker-compose up -d --build